### ISSUE TITLE
Spring Cloud 微服务怎么接入opensergo?

### ISSUE THREAD

**Issue by jujunchen** [opensergo/opensergo-specification#16]
Spring Cloud 微服务怎么接入opensergo

**Comment by sczyh30** [comment]
Hi, we've discussed the structure of OpenSergo SDK in the previous community meeting (refer #17). Now the community is working on the initial version of OpenSergo Java SDK and operator. We'll sync the progress with Spring Cloud Alibaba and other communities soon. Discussions and contributions are welcomed.

**Comment by sczyh30** [comment]
@jujunchen Now you could refer to:

* https://opensergo.io/zh-cn/docs/quick-start/java/quick-start-spring-cloud-alibaba/
* https://github.com/alibaba/spring-cloud-alibaba/blob/2.2.x/spring-cloud-alibaba-examples/governance-example/label-routing-example/readme-zh.md
