### ISSUE TITLE
流量路由标准中样例yaml是否有误

### ISSUE THREAD

**Issue by xierunzi** [opensergo/opensergo-specification#45]
![image](https://user-images.githubusercontent.com/65679911/194704351-8fedad7b-a4f3-4225-a042-bcdcc1123e7e.png)
为何这里说header是123的流量访问gray标签的实例，但yaml给了一个正则的样例？是我理解有误吗

**Comment by CH3CHO** [comment]
感觉是不太对啊

**Comment by sczyh30** [comment]
Fancy a PR to fix it? :)
